baseurl = "https://jjasonclark.com/"
languagecode = "en-us"
title = "JJasonClark.com"
publishdir = "public"
layoutdir = "layouts"
timezone = "America/Vancouver"
encoding = "utf-8"
DisqusShortname = "jjasonclark"
theme = ["basic-min"]

[params]
email = "jason@jjasonclark.com"
title = "JJasonClark.com"
description = "Stuff I have time to write about\n"
mainSections = ["post"]
twitter = "jjasonclark"
github =  "jjasonclark"
googleAnalytics  = "UA-12083278-1"
disqusShortname  = "jjasonclark"
bitcoin = "14622f9QThq7ieB1jJ3rHy9Xx4jK8UN7DV"
showAds = true
showComments = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[author]
name = "Jason Clark"
email = "jason@jjasonclark.com"

[markup]
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = false
    style = "monokai"
    tabWidth = 2
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
